### ISSUE TITLE
Respect markdown quote blocks

### ISSUE THREAD

**Issue by gfontenot** [gfontenot/hfold#8]
We should't wrap these

**Comment by gabebw** [comment]
This seems like it's addressed by #7

**Comment by gfontenot** [comment]
I don't think so. I think the parser rules will be subtly different. For code blocks it's "stop wrapping when you see 3 backticks, start when you see the next 3 backticks". This is basically just "don't wrap lines that start with `>`"

**Comment by gabebw** [comment]
Oops, you're right. I read them as the exact same issue wording. My mistake.
